volumes:
  postgres-data:
    driver: local

services:
  cars.api:
    image: cars.api
    build:
      context: .
      dockerfile: Cars.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    networks:
      - db_networks
      

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cars-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_networks  
    
networks:
  db_networks:
    driver: bridge