version: '3.9'

volumes:
  postgres-data:
    driver: local

services:
  database:
    container_name: cars-db
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root